blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://stackoverflow.com/questions/tagged/typescript
    about: Please ask and answer questions here.
  - name: TypeScript FAQ
    url: https://github.com/microsoft/TypeScript/wiki/FAQ
    about: Please check the FAQ before filing new issues