name: Accept Baselines and Fix Lints

on:
  workflow_dispatch: {}

permissions:
  contents: read

# Ensure scripts are run with pipefail. See:
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          token: ${{ secrets.TS_BOT_GITHUB_TOKEN }}
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0

      - name: Configure Git, Run Tests, Update Baselines, Apply Fixes
        run: |
          git config user.email "typescriptbot@microsoft.com"
          git config user.name "TypeScript Bot"
          npm ci
          git rm -r --quiet tests/baselines/reference
          npx hereby runtests-parallel --ci --fix || true
          npx hereby baseline-accept
          git add ./src
          git add ./tests/baselines/reference
          git diff --cached
          git commit -m "Update Baselines and/or Applied Lint Fixes"
          git push
