name: Accept Baselines and Fix Lints

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3

    - name: Configure Git, Run Tests, Update Baselines, Apply Fixes
      run: |
        git config user.email "typescriptbot@microsoft.com"
        git config user.name "TypeScript Bot"
        npm install
        git rm -r --quiet tests/baselines/reference :^tests/baselines/reference/docker :^tests/baselines/reference/user
        npx hereby runtests-parallel --ci --fix || true
        npx hereby baseline-accept
        git add ./src
        git add ./tests/baselines/reference
        git diff --cached
        git commit -m "Update Baselines and/or Applied Lint Fixes"
        git push
