name: Sync branch with master

on:
  repository_dispatch:
    types: sync-branch
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Target Branch Name'
        required: true

permissions:
  contents: read

# Ensure scripts are run with pipefail. See:
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/setup-node@v3
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch_name || github.event.client_payload.branch_name }}
        fetch-depth: 0
    # This does a test post-merge and only pushes the result if the test succeeds
    # required client_payload members:
    # branch_name - the target branch
    - run: |
        git config user.email "typescriptbot@microsoft.com"
        git config user.name "TypeScript Bot"
        git fetch origin main
        git merge origin/main --no-ff
        npm ci
        npm test
        git push
