name: Sync branch with master

on:
  repository_dispatch:
    types: [sync-branch]
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Target Branch Name'
        required: true

permissions:
  contents: read

# Ensure scripts are run with pipefail. See:
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ github.event.inputs.branch_name || github.event.client_payload.branch_name }}
          filter: blob:none # https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/
          fetch-depth: 0 # Default is 1; need to set to 0 to get the benefits of blob:none.
          token: ${{ secrets.TS_BOT_GITHUB_TOKEN }}
      # required client_payload members:
      # branch_name - the target branch
      - run: |
          git config user.email "typescriptbot@microsoft.com"
          git config user.name "TypeScript Bot"
          git fetch origin main
          git merge origin/main --no-ff
          npm ci
          npx hereby LKG
          git add --force ./lib
          git commit -m 'Update LKG'
          git push
