name: Twoslash Code Sample Repros

on:
  push:
    branches:
      - orta-twoslash-repros
  schedule:
    - cron:  '0 8 * * *'
  repository_dispatch:
    types: run-twoslash-repros
  workflow_dispatch:
    inputs:
      issue:
        description: Limits run to a single issue.
        required: false
        type: string
      bisect:
        description: If set, runs a git bisect on an existing repro. Requires 'issue' to be set. Value can be revision labels (e.g. `good v4.7.3 bad main`) or `true` to infer bisect range.
        required: false
        type: string

jobs:
  run:
    if: ${{ github.repository == 'microsoft/TypeScript' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: ${{ github.events.input.bisect && '0' || '1' }}
    - uses: actions/setup-node@v3
    - uses: microsoft/TypeScript-Twoslash-Repro-Action@master
      with:
        github-token: ${{ secrets.TS_BOT_GITHUB_TOKEN }}
        issue: ${{ github.event.inputs.issue }}
        bisect: ${{ github.event.inputs.bisect }}
