name: Update LKG

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use node version 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
        registry-url: https://registry.npmjs.org/

    - name: Configure Git and Update LKG
      run: |
        git config user.email "typescriptbot@microsoft.com"
        git config user.name "TypeScript Bot"
        npm ci
        gulp LKG
        npm test
        git diff
        git add ./lib
        git commit -m "Update LKG"
        git push
